# Generated by Django 3.0.5 on 2021-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dealerinfo',
            },
        ),
    ]
