# Generated by Django 3.0.5 on 2021-06-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(unique=True)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'customerinfo',
            },
        ),
    ]
