# Generated by Django 3.0.5 on 2021-06-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
