# Generated by Django 3.0.5 on 2021-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_delete_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.IntegerField(unique=True)),
                ('mname', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'medicineinfo',
            },
        ),
    ]
