# Generated by Django 3.0.5 on 2021-06-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone_no', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'purchaseinfo',
            },
        ),
    ]
