# Generated by Django 3.0.5 on 2021-06-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='fname',
            new_name='dname',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='lname',
        ),
    ]
