# Generated by Django 3.0.5 on 2021-06-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_auto_20210608_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
