# Generated by Django 3.0.5 on 2021-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(unique=True)),
                ('mname', models.CharField(max_length=30)),
                ('dname', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'purchaseinfo',
            },
        ),
    ]
