# Generated by Django 3.0.5 on 2021-06-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_auto_20210610_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custpurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(unique=True)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('mname', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'custpurchaseinfo',
            },
        ),
    ]
